---
title: "November Meeting - Appendix"
output:
  bookdown::word_document2:
      toc: false
      toc_depth: 3
      reference_docx: word-styles-reference-01.docx
  bookdown::pdf_document2:
  bookdown::html_document2:
      toc: true
      toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
cohort2table1 <- read.csv(here::here("output","cohort2_table1.csv"),header=FALSE)
```

```{r}
cohort2table1 <- data.table::transpose(cohort2table1)
colnames(cohort2table1) <- as.character(unlist(cohort2table1[1,]))
cohort2table1 = cohort2table1[-1, ]
cohort2table1 <- cohort2table1[c(1:14,18:19,15:17),]

rownames(cohort2table1)[1] <- "N"
rownames(cohort2table1)[2] <-"Median year of prescription"
rownames(cohort2table1)[3] <-"Female"
rownames(cohort2table1)[4] <-"Age"
rownames(cohort2table1)[5] <-"CAD"
rownames(cohort2table1)[6] <-"CBS"
rownames(cohort2table1)[7] <-"CVD"
rownames(cohort2table1)[8] <-"Charlson"
rownames(cohort2table1)[9] <-"IMD-2010"
rownames(cohort2table1)[10] <-"Consulation rate"
rownames(cohort2table1)[11] <-"Alcohol (ever)"
rownames(cohort2table1)[12] <-"Smoking (ever)"
rownames(cohort2table1)[13] <-"BMI"
rownames(cohort2table1)[14] <-"PAD"
rownames(cohort2table1)[15] <-"Hypertension"
rownames(cohort2table1)[16] <-"Stopped"
rownames(cohort2table1)[17] <-"Added"
rownames(cohort2table1)[18] <-"Switched"
rownames(cohort2table1)[19] <-"Other drug within 5yrs"
cohort2table1 <- cohort2table1[,-1]

cohort2table1 <- cohort2table1[,c(9,6,8,1:5,7)]

knitr::kable(cohort2table1, booktabs = TRUE, caption = 'Patient characteristics of Cohort 2', row.names = TRUE)
```


